# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
  clients:
    default: { host: localhost, port: 9200 }
  serializer: ~
  indexes:
    app:
      finder: ~
      types:
        series:
          serializer:
            groups: [elastica]
          persistence:
            driver: orm
            model: App\Entity\Series
            finder: ~
            provider: ~
            listener: ~